/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.ContenedorOportunidades;
import modelo.ContenedorPrograma;
import modelo.Datos;
import modelo.ExcepcionNumero;
import modelo.ExcepcionPrograma;
import modelo.ExcepcionZona;

/**
 *
 * @author admin
 */
public class CrearOportunidad extends javax.swing.JFrame
{

    /**
     * Creates new form Vista
     * @param controlador
     */
    public CrearOportunidad(Controlador controlador, Datos datos)
    {
        this.controlador = controlador;
        this.datos = datos;
        cargarImagen = new CargarImagen();
        initComponents();
    }
    
    /**
     * Contructor con argumetos hecho para modificar las oportunidades
     * @param controlador
     * @param ciudad 
     * @param pais 
     * @param descripcion 
     * @param enlace 
     * @param programa 
     * @param zona 
     * @param numero 
     */
    public CrearOportunidad(Controlador controlador, Datos datos, String ciudad, String pais, String descripcion, String enlace, int programa, File ficheroImagen, int zona, int numero)
    {
        initComponents();
        cargarImagen = new CargarImagen();
        
        this.controlador = controlador;
        this.datos = datos;
        
        textoCiudad.setText(ciudad);
        textoPais.setText(pais);
        textoDescripcion.setText(descripcion);
        textoEnlace.setText(enlace);
        comboBoxPrograma.setSelectedIndex(programa);
        comboBoxZona.setSelectedIndex(zona);
        this.ficheroImagen = ficheroImagen;
        
        if (numero == 0)
            jRadioButton0.setSelected(true);
        else if (numero == 1)
            jRadioButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textoCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoPais = new javax.swing.JTextField();
        botonCrearHTML = new javax.swing.JButton();
        comboBoxPrograma = new javax.swing.JComboBox<>();
        comboBoxZona = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton0 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        textoEnlace = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CrearOportunidad");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        textoCiudad.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Ciudad:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("País:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descripción:");

        textoPais.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        botonCrearHTML.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        botonCrearHTML.setText("¡CREAR HTML!");
        botonCrearHTML.setEnabled(false);
        botonCrearHTML.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonCrearHTMLActionPerformed(evt);
            }
        });

        comboBoxPrograma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBoxPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Global Talent", "Global Entrepeneur", "Globla Citizen" }));

        comboBoxZona.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboBoxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "África", "Oriente Medio y Norte de África", "Centro y Este de Europa", "Asía-Pacífico", "Europa Occidental y América del Norte", "Latinoamérica" }));
        comboBoxZona.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Programa:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Zona del mundo:");

        buttonGroup1.add(jRadioButton0);
        jRadioButton0.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton0.setSelected(true);
        jRadioButton0.setText("Oportunidad 0");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("Oportunidad 1");

        jToggleButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton1.setText("Seleccionar Imagen");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton1ActionPerformed(evt);
            }
        });

        textoEnlace.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Enlace:");

        textoDescripcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(18, 18, 18)
                                .addComponent(botonCrearHTML))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboBoxZona, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textoEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearHTML)
                    .addComponent(jToggleButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearHTMLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCrearHTMLActionPerformed
    {//GEN-HEADEREND:event_botonCrearHTMLActionPerformed
        int programa;
        switch (comboBoxPrograma.getSelectedIndex())
        {
            case 0:
                programa = ContenedorOportunidades.GLOBAL_TALENT;
                break;
            case 1:
                programa = ContenedorOportunidades.GLOBAL_ENTREPENEUR;
                break;
            case 2:
                programa = ContenedorOportunidades.GLOBAL_CITIZEN;
                break;
            default:
                programa = -1;
                break;
        }
        
        int zona;
        switch (comboBoxZona.getSelectedIndex())
        {
            case 0:
                zona = ContenedorPrograma.AFRICA;
                break;
            case 1:
                zona = ContenedorPrograma.ORIENTE_MEDIO_NORTE_AFRICA;
                break;
            case 2:
                zona = ContenedorPrograma.CENTRO_ESTE_EUROPA;
                break;
            case 3:
                zona = ContenedorPrograma.ASIA_PACIFICO;
                break;
            case 4:
                zona = ContenedorPrograma.EUROPA_OCCIDENTAL_AMERICA_NORTE;
                break;
            case 5:
                zona = ContenedorPrograma.LATINOAMERICA;
                break;
            default:
                zona = -1;
                break;
        }
        
        int numero;
        
        if (jRadioButton0.isSelected())
            numero = 0;
        else if (jRadioButton1.isSelected())
            numero = 1;
        else
            numero = -1; //número que indica error
        try
        {
            controlador.añadirOportunidad(textoCiudad.getText(), textoPais.getText(), textoDescripcion.getText(), textoEnlace.getText(), ficheroImagen, programa, zona, numero);
            JOptionPane.showMessageDialog(cargarImagen, "Operación terminada con éxito");
            this.dispose();
            ventanaExterna = new VentanaPrincipal (controlador, datos);
        } catch (IOException ex)
        {
            JOptionPane.showMessageDialog(cargarImagen, "Error copiando imagen.");
        } catch (ExcepcionNumero | ExcepcionPrograma | ExcepcionZona ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_botonCrearHTMLActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton1ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton1ActionPerformed
        ficheroImagen = cargarImagen.dameImagen();
        botonCrearHTML.setEnabled(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        
        this.dispose();
        ventanaExterna = new VentanaPrincipal (controlador, datos);
        ventanaExterna.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearHTML;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxPrograma;
    private javax.swing.JComboBox<String> comboBoxZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton0;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoDescripcion;
    private javax.swing.JTextField textoEnlace;
    private javax.swing.JTextField textoPais;
    // End of variables declaration//GEN-END:variables
    private Controlador controlador;
    private File ficheroImagen;
    private CargarImagen cargarImagen;
    private JFrame ventanaExterna;
    private Datos datos;
}
